[package]
name = "yaso"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
libc = "0.2"
once_cell = "1"
rquickjs = { version = "0.5", features = ["bindgen", "full-async", "rust-alloc"] }
tokio = { version = "1", features = ["full"] }
